"""Add session_id to Cart model

Revision ID: 441e3fa849a6
Revises: 323943bc1023
Create Date: 2024-09-01 21:07:09.867444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441e3fa849a6'
down_revision = '323943bc1023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
